### ISSUE TITLE
improve the code in take_snapshot

### ISSUE THREAD

**Issue by maelle** [lockedata/cransays#1]
* remove repetition of code

* have a better format for the human subfolders (DSok/ -> DS/ok)

* for each line add a direct link to the corresponding folder

**Comment by maelle** [comment]
Contributions welcome for any of these items

**Comment by mitchelloharawild** [comment]
A big simplification would be to use `utils::read.table` instead of `curl::curl`, because the ftp format is textual separated by spaces. As it would then be a data.frame, extracting folders would be much simpler.

I'm happy to submit a PR for this if it's a good idea.

``` r
read.table("ftp://cran.r-project.org/incoming/")
#>            V1 V2   V3   V4   V5  V6 V7    V8      V9
#> 1  drwxrwsr-x  6 1021 1001 4096 Apr 23 08:43      DS
#> 2  drwxrwsr-x  2 1001 1001 4096 Apr 11 16:53      KH
#> 3  drwxr-sr-x  2 1023 1001 4096 Sep 30 18:44      SH
#> 4  drwxrwsr-x  3 1010 1001 4096 Sep 20 00:25      UL
#> 5  drwxrwsr-x  2 1010 1001 4096 Oct  9 13:04 archive
#> 6  drwxrwsr-x  2 1010 1001 4096 Oct  9 13:19 inspect
#> 7  drwxrwsr-x  2 1010 1001 4096 Oct  9 06:39 pending
#> 8  drwxrwsr-x  2  105 1001 4096 Oct  9 13:40 pretest
#> 9  drwxrwsr-x  2 1010 1001 4096 Oct  9 13:10 publish
#> 10 drwxrwsr-x  2 1010 1001 4096 Oct  9 11:53 recheck
```

Created on 2018-10-09 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by maelle** [comment]
It is an exvellent idea!
