### ISSUE TITLE
Dashboard not updating?

### ISSUE THREAD

**Issue by jennybc** [lockedata/cransays#24]
The dashboard has been stuck at 2019-05-23 11:41 UTC+0000 for a while now.

**Comment by maelle** [comment]
Thanks, on it, hopefully I can solve the deploy error.

**Comment by jennybc** [comment]
The travis log suggests it's a problem with the ssh keys. Did you set this up via `usethis::use_pkgdown_travis()` and did that seem to go well?

**Comment by maelle** [comment]
I created new ones with `travis::use_travis_deploy()` this morning 😢 but will try again with your function.

**Comment by jennybc** [comment]
Ah, now that I reread the source of `use_pkgdown_travis()`, I see that it does a few things but ultimately tells you to execute `travis::use_travis_deploy()`.  And that is the function that sets up the ssh keys.

**Comment by maelle** [comment]
Thanks. I'll look into other solutions then, maybe not before tomorrow.

**Comment by maelle** [comment]
What surprises me the most is that
- it used to work and my access rights did not change
- pkgdown deploy function looks for ssh keys before doing anything (and i see the id_rsa environment variable).

**Comment by jennybc** [comment]
Perhaps you should clear out all the existing secure env vars so that `travis::use_travis_deploy()` is starting from a fresh slate, which is probably what it expects.

**Comment by maelle** [comment]
done but I think it deleted the existing keys. I am starting to wonder whether there is something special on Travis macOS ssh/git setup (that on top of being special would be very new since that's a new issue... I'll try to look through everything again tomorrow with a clear mind!).

Note that this package uses macOS because the ftp stuff did not work on Ubuntu.

**Comment by jennybc** [comment]
Yeah, perhaps the OS the problem. Just observing from the outside, getting the ftp call to work from Ubuntu sounds easier to me than sorting the ssh stuff out on macOS, when the only way to debug things is to read travis log files. But I realize you maybe have studied this already and have a reason to think macOS will be easier.

**Comment by maelle** [comment]
The FTP call could just not work, it was a firewall thing Travis has for Ubuntu. Anyhow, let's hope I can solve this tomorrow, thanks for your help! :muscle:

**Comment by maelle** [comment]
Guess what, git2r saved me! :wink: I switched back to using tic, instead of deploying via pkgdown. It turned out to be what created the bug:

* pkgdown uses the system git (with which the ssh-askpass issue appears),

* tic uses git2r.

I had removed tic when fixing the problem a tic deprecated function created. I worried about future other deprecations, because I thought things might change in tic (that's under review at the moment) during my maternity leave... we shall see.
